### PR TITLE
Remove trailing slashes to adopt aphrodite-engine expected syntax

### PR DESCRIPTION
**Pull request by TeaSitta**
First git PR, be gentle.

Tested for a day with aphrodite. Changes halve worker to aphrodite traffic, overall http jobs, and aphrodite console spam.

Not tested with anything else that may still use this old worker.

### CODE REVIEW

**Comment by henk717** [comment]
This might break United and will need to be tested prior to merging.

**Comment by zten** [comment]
I had fixed this with haproxy to rewrite the requests without slashes, but fixing the scribe instead would be nice.

**Comment by db0** [comment]
@henk717 any opposition to merge as it seems to be tested?

**Comment by henk717** [comment]
Should be fine

**Pull request merged**
